name: spw4-game2048
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: checkout
        uses: actions/checkout@v3
      - name: compile
        run: mvn compile
      - name: artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled program
          path: 'target/*'
          retention-days: 5
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: checkout
        uses: actions/checkout@v3
      - name: test
        run: mvn test
      - name: artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: 'target/*'
          retention-days: 5
